services:
  - type: web
    name: dialog-watch-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dialog-watch-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  # Configuration du worker
  - type: worker
    name: dialog-watch-worker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rake solid_queue:start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dialog-watch-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: dialog-watch-db
    plan: free